name: black-merge
on: [pull_request]

jobs:
   bm:
     name: Black merge
     
     steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
          python-version: '3.10' 
     - run: python auto-merge.py
